/* Definitions for the globals that geotop.cc owns.
 *
 * The oracle links every GEOtop translation unit except geotop.cc (which holds
 * main()), so the globals that file defines have to be provided here.
 *
 * Most are only storage. The three "novalue" sentinels are NOT: GEOtop sets
 * them at the top of main() (geotop.cc:157-159) and code all over the model
 * compares against them, so leaving them zero would make every "is this
 * absent?" test wrong. gt_inpts_open in particular fills missing keywords with
 * number_novalue. They are initialised here to exactly what main() assigns.
 *
 * Mirrors geotop.cc:57-99 and :157-159.
 */

#include "struct.geotop.h"
#include "tabs.h"

#include <cstdio>
#include <ctime>
#include <memory>
#include <sys/stat.h>

long number_novalue = -9999;
long number_absent = -9998;
char *string_novalue = assign_string("none");

std::unique_ptr<T_INIT> UV;

char *logfile = const_cast<char *>("/dev/null");
char **files;

long Nl, Nr, Nc;
double t_meteo, t_energy, t_water, t_sub, t_sup, t_blowingsnow, t_out;

double **odpnt, **odp;
long *opnt, nopnt;
short *ipnt, *ibsn;
char **hpnt;

double *odbsn, *odb;
long *obsn, nobsn;
char **hbsn;

long *osnw, nosnw;
char **hsnw;

long *oglc, noglc;
char **hglc;

long *osl, nosl;
char **hsl;

FILE *ffbas, *ffpoint, *ffT, *ffTav, *ffpsi, *ffpsitot, *ffliq, *ffliqav,
        *ffice, *fficeav, *ffsnowT, *ffsnowl, *ffsnowi, *ffsnowd, *ffglac;

long i_sim = 0, i_run, i_sim0, i_run0;

// Both are only ever fopen'd and fprintf'd to on an error/completion path
// (e.g. tabs.cc's duplicate-timestamp check); /dev/null discards them safely,
// the same choice already made for `logfile` above.
char *SuccessfulRunFile = const_cast<char *>("/dev/null");
char *FailedRunFile = const_cast<char *>("/dev/null");

// Some linked functions write scratch/log files here unconditionally (e.g.
// clouds.cc's cloudiness()/find_cloudiness() append to WORKING_DIRECTORY +
// "clouds.txt" with no way to disable it) -- a null WORKING_DIRECTORY (main()
// is the only place that would normally set it) segfaults the first time one
// of those runs. Point it at a scratch directory the oracle creates on load,
// well away from both the reference checkout and this repo -- the file
// content is never read back, only its existence matters.
namespace
{
const char *init_working_directory()
{
    const char *dir = "/tmp/geotop_oracle_scratch/";
    mkdir(dir, 0755);  // ignore EEXIST and any other failure: best-effort
    return dir;
}
}  // namespace

const char *WORKING_DIRECTORY = init_working_directory();

time_t start_time;
double elapsed_time, elapsed_time_start, cum_time, max_time;

/* version.cc is generated by meson and only geotop.cc uses it. */
const char *version() { return "oracle"; }
const char *commit() { return "oracle"; }
