#!/usr/bin/env python3
"""Generate src/geotop_py/io/keywords.py from the GEOtop v3.0 sources.

The keyword tables and their defaults are not transcribed by hand: this reads
them out of ``keywords.h`` and ``parameters.cc`` so regenerating after an
upstream change is a command, not an audit.

* **Names** come from ``keywords.h``. Order is meaning, not presentation: the
  index of a name is the ``cod`` that ``assign_numeric_parameters`` uses to
  reach it. ``tests/test_keywords.py`` checks the generated list against the
  compiled model, so a silent drift fails the suite.
* **Defaults** are scraped from the ``assignation_number(cod, j, ..., default,
  flag)`` calls. Most resolve to a single literal. Those that do not are
  reported rather than guessed -- see DEFAULTS_AMBIGUOUS in the output.

    python3 -m tools.gen_keywords [--check]

``--check`` regenerates in memory and fails if the committed file is stale.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from tools.paths import GEOTOP_SRC

DEFAULT_SRC = str(GEOTOP_SRC)
TARGET = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "src", "geotop_py", "io", "keywords.py")


def read_tables(src: str):
    """The two keyword arrays of keywords.h, in declaration order."""
    text = open(os.path.join(src, "src", "geotop", "keywords.h"),
                errors="replace").read()

    def block(name: str):
        start = text.index(f"{name}[")
        body = text[text.index("{", start) + 1:text.index("};", start)]
        return re.findall(r'"([^"]*)"', body)

    return block("keywords_num"), block("keywords_char")


def _split_args(text: str):
    parts, depth, buf = [], 0, ""
    for ch in text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(buf.strip())
            buf = ""
        else:
            buf += ch
    parts.append(buf.strip())
    return parts


# GEOtop writes its literals C-style, including the trailing-dot form (`0.`,
# `1.E-4`), which a naive "digits then optional dot then digits" pattern misses.
_NUM = r"-?(?:[0-9]+\.?[0-9]*|\.[0-9]+)(?:[eE][-+]?[0-9]+)?"
_LITERAL = re.compile(rf"^\(?\s*(?:\(\s*double\s*\)\s*)?\(?\s*({_NUM})\s*\)?$")


def read_defaults(src: str, keywords_num):
    """Scrape (keyword -> default) out of assign_numeric_parameters.

    Returns ``(defaults, ambiguous, unresolved)``:
    ``defaults`` maps a keyword to its single literal default; ``ambiguous``
    maps a keyword to the set of default expressions found, when more than one;
    ``unresolved`` lists calls whose keyword index is computed at runtime
    (loops over land-cover classes, soil types, meteo stations).
    """
    text = open(os.path.join(src, "src", "geotop", "parameters.cc"),
                errors="replace").read()
    start = text.index("void assign_numeric_parameters")
    end = start + re.search(r"\n\}\n", text[start:]).end()
    flat = re.sub(r"\s+", " ", text[start:end])

    pattern = re.compile(
        r"\bcod\s*=\s*(\d+)\s*;|assignation_number\s*\(([^;]*?)\)\s*[;,)]")

    found, unresolved = {}, []
    current = None
    for match in pattern.finditer(flat):
        if match.group(1) is not None:
            current = int(match.group(1))
            continue
        args = _split_args(match.group(2))
        if len(args) < 6:
            continue
        index, default = args[0], args[5]
        if index.isdigit():
            cod = int(index)
        elif index == "cod" and current is not None:
            cod = current
        else:
            unresolved.append((index, default))
            continue
        if 0 <= cod < len(keywords_num):
            found.setdefault(keywords_num[cod], []).append(default)

    defaults, ambiguous = {}, {}
    for name, exprs in found.items():
        literals = {e for e in exprs}
        if len(literals) == 1:
            m = _LITERAL.match(exprs[0])
            if m:
                defaults[name] = float(m.group(1))
            elif "number_novalue" in exprs[0]:
                defaults[name] = None            # explicit "absent"
            else:
                ambiguous[name] = sorted(literals)
        else:
            ambiguous[name] = sorted(literals)
    return defaults, ambiguous, unresolved


def render(keywords_num, keywords_char, defaults, ambiguous, unresolved) -> str:
    def as_list(name, values):
        body = "".join(f'    "{v}",\n' for v in values)
        return f"{name} = [\n{body}]\n"

    lines = [
        '"""GEOtop v3.0 keyword tables and their defaults.',
        "",
        "GENERATED by tools/gen_keywords.py -- do not edit by hand.",
        "Regenerate with ``python3 -m tools.gen_keywords`` after an upstream change;",
        "``--check`` fails if this file is stale.",
        "",
        "The index of a name in KEYWORDS_NUM is the ``cod`` that",
        "``assign_numeric_parameters`` uses to reach it, so the order carries meaning.",
        "``tests/test_keywords.py`` pins both lists against the compiled model.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Dict, List, Optional",
        "",
        as_list("KEYWORDS_NUM", keywords_num),
        as_list("KEYWORDS_CHAR", keywords_char),
        "#: Default value per numeric keyword, scraped from the",
        "#: ``assignation_number(..., default, ...)`` calls. ``None`` means GEOtop",
        "#: passes number_novalue, i.e. the parameter stays absent unless declared.",
        "DEFAULTS: Dict[str, Optional[float]] = {",
    ]
    for name in sorted(defaults):
        lines.append(f"    {name!r}: {defaults[name]!r},")
    lines += [
        "}",
        "",
        "#: Keywords whose default is not a single literal -- GEOtop computes it, or",
        "#: uses a different one per component (typically \"default to the previous",
        "#: component\"). Listed rather than flattened: porting the parameter means",
        "#: reading the C++ block, and a wrong scalar here would look authoritative.",
        "DEFAULTS_AMBIGUOUS: Dict[str, List[str]] = {",
    ]
    for name in sorted(ambiguous):
        lines.append(f"    {name!r}: {ambiguous[name]!r},")
    lines += [
        "}",
        "",
        "#: assignation_number calls whose keyword index is computed at runtime",
        "#: (loops over land-cover classes, soil types, meteo stations), as",
        "#: ``(index expression, default expression)``.",
        f"DEFAULTS_COMPUTED_INDEX = {sorted(set(unresolved))!r}",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--src", default=os.environ.get("GEOTOP_SRC", DEFAULT_SRC),
                   help=f"GEOtop checkout root (default: {DEFAULT_SRC})")
    p.add_argument("--check", action="store_true",
                   help="fail if the committed file differs from a fresh render")
    args = p.parse_args(argv)

    if not os.path.isdir(os.path.join(args.src, "src", "geotop")):
        print(f"GEOtop sources not found under {args.src}", file=sys.stderr)
        return 2

    keywords_num, keywords_char = read_tables(args.src)
    defaults, ambiguous, unresolved = read_defaults(args.src, keywords_num)
    text = render(keywords_num, keywords_char, defaults, ambiguous, unresolved)

    if args.check:
        current = open(TARGET).read() if os.path.exists(TARGET) else ""
        if current != text:
            print(f"{TARGET} is stale; run python3 -m tools.gen_keywords",
                  file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date")
        return 0

    with open(TARGET, "w") as fh:
        fh.write(text)
    print(f"wrote {TARGET}: {len(keywords_num)} numeric, {len(keywords_char)} string, "
          f"{len(defaults)} defaults, {len(ambiguous)} ambiguous, "
          f"{len(set(unresolved))} computed-index")
    return 0


if __name__ == "__main__":
    sys.exit(main())
